Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64" 
    config.vm.define "server" do |server| 
    server.vm.hostname = "server.loc" 
    server.vm.network "private_network", ip: "192.168.56.10", adapter: 2, virtualbox__intnet: "vpn"
    server.vm.network "private_network", ip: "192.168.50.10", adapter: 3, virtualbox__intnet: "ansible"
    server.vm.provision "shell", inline: <<-SHELL
          sed -i 's/^#PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
          systemctl restart sshd.service
          SHELL
    end 
    
    config.vm.define "client" do |client| 
    client.vm.hostname = "client.loc" 
    client.vm.network "private_network", ip: "192.168.56.20", adapter: 2, virtualbox__intnet: "vpn"
    client.vm.network "private_network", ip: "192.168.50.20", adapter: 3, virtualbox__intnet: "ansible"
    client.vm.provision "shell", inline: <<-SHELL
          sed -i 's/^#PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
          systemctl restart sshd.service
          SHELL
    end 
end
    