---
- hosts: all # part running on all hosts
  become: true
  tasks:
  - name: set vlans
    template: 
      src: "50-cloud-init.yaml.j2"
      dest: /etc/netplan/50-cloud-init.yaml
      owner: root
      group: root
      mode: 0644
    when: "'servers' in group_names"
  - name: set up eth1,eth2
    template: 
      src: "{{ item }}"
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - ifcfg-eth1
      - ifcfg-eth2
    when: (ansible_hostname != "office1Router") and (inventory_hostname in groups["routers"])
  - name: set bond
    template: 
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname != "office1Router") and (inventory_hostname in groups["routers"])
  - name: restart hosts for bond0
    reboot:
      reboot_timeout: 3600
    when: (ansible_hostname != "office1Router") and (inventory_hostname in groups["routers"])
  - name: apply set up vlan2
    shell: netplan apply
    become: true
    when: (ansible_os_family == "Debian")

