# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.host_name = "mdamd"
  config.vm.disk :disk, size: "10GB", name: "disk1"
  config.vm.disk :disk, size: "10GB", name: "disk2"
  config.vm.disk :disk, size: "10GB", name: "disk3"
  config.vm.disk :disk, size: "10GB", name: "disk4"
  config.vm.disk :disk, size: "10GB", name: "disk5"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end
  config.vm.provision "update", type: "shell", inline: <<-SHELL
    #apt-get update
    #sudo apt-get install net-tools
  SHELL
  config.vm.provision "mdadm", type: "shell", inline: <<-SHELL
    #sudo lsblk
    sudo mdadm --create --verbose /dev/md127 -l 5 -n 5 /dev/sd{b,c,d,e,f}
    #sudo cat /proc/mdstat
    sudo echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
    sudo mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
  SHELL
  config.vm.provision "mdadm-status", type: "shell", inline: <<-SHELL
    #sudo cat /proc/mdstat
  SHELL
  config.vm.provision "parted_gpt", type: "shell", inline: <<-SHELL
    sudo parted -s /dev/md127 mklabel gpt
    #sudo parted -l
  SHELL
  config.vm.provision "parted_mkpart", type: "shell", inline: <<-SHELL
    sudo parted /dev/md127 mkpart primary ext4 0% 20%
    sudo parted /dev/md127 mkpart primary ext4 20% 40%
    sudo parted /dev/md127 mkpart primary ext4 40% 60%
    sudo parted /dev/md127 mkpart primary ext4 60% 80%
    sudo parted /dev/md127 mkpart primary ext4 80% 100%
    #sudo parted -l
  SHELL
  config.vm.provision "mkfs_mount", type: "shell", inline: <<-SHELL
    for i in $(seq 1 5)
      do
       FILE="/dev/md127p$i"
       if [[ -b "$FILE" ]]; then
        sudo mkfs.ext4 /dev/md127p$i
        sudo mkdir -p /raid/part$i
        sudo mount /dev/md127p$i /raid/part$i
        sudo ls -l /raid/part$i/
       else
        echo "$FILE problem"
       fi
    done
  SHELL
end
